issues:
  - type: bug
    name: "ğŸ› Bug report"
    about: "Report a bug to help us improve"
    title: "Bug: "
    labels: ["bug"]
    assignees: ['']
    template: "bug_report.md"

  - type: feature
    name: "âœ¨ Feature request"
    about: "Suggest an idea for this project"
    title: "Feature: "
    labels: ["feat request"]
    assignees: ['']
    template: "feature_request.md"

  - type: improvement
    name: "ğŸ›  Improvement"
    about: "Improve an existing feature"
    title: "Improvement: "
    labels: ["enhancement"]
    assignees: ['']
    template: "improve_existing_functionality.md"

